spring:
  application:
    name: "Flowly"

server:
  port: ${SERVER_PORT:8080}

app:
  service:
    host: localhost
    port: 6979
  cors:
    allowed-origins: "${APP_CORS_ALLOWED_ORIGINS:*}"

management:
  server:
    port: ${APP_MANAGEMENT_PORT:9092}
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "always"
